[package]
name = "watermark"
version = "0.1.0"
authors = ["William Azevedo <willianray@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
raster = "0.2.0"
threadpool = "1.7.1"
num_cpus = "1.11.0"
